server:
  port: 0

spring:
#  profiles:
#    active: local
  application:
    name: post-svc
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

